---
############ Ansible Installation (Move to separate role later) ###############

- name: Install epel-release 
  yum:
    name: epel-release
    state: latest
  become: yes
  become_method: su

- name: Install Ansible
  yum:
    name: ansible
    state: latest
  become: yes
  become_method: su


